main: uk.co.matthogan.modchat.Main
name: ModChat
version: 2.0-SNAPSHOT
description: ModChat - Allows you to privately communicate with other moderators.
author: n7mathew7n (Matthew Hogan)
website: http://matthogan.co.uk